[slave]
arn   = "arn:aws:iam::415077340068:instance-profile/SlaveTheRipper"
role  = "SlaveTheRipper"
image = "ami-7abd0209" # CentOS 7 (x86_64) - with Updates HVM for EU (Ireland)
type  = "t2.micro"

[master]
arn  = "arn:aws:iam::415077340068:instance-profile/MasterTheRipper"
role = "MasterTheRipper"

[aws]
region = "eu-west-1"
